export const NOT_SIGNED_IN = '[AUTH] NOT_SIGNED_IN';
export const RECEIVE_USER_PROFILE = '[AUTH] RECEIVE_USER_PROFILE';
export const SAVE_REDIRECT = '[AUTH] SAVE_REDIRECT';
export const START_SIGN_IN = '[AUTH] START_SIGN_IN';
export const SIGN_IN = '[AUTH] SIGN_IN';
export const SIGN_IN_SUCCESS = '[AUTH] SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = '[AUTH] SIGN_IN_FAIL';
export const START_SIGN_UP = '[AUTH] START_SIGN_UP';
export const SIGN_UP = '[AUTH] SIGN_UP';
export const SIGN_UP_SUCCESS = '[AUTH] SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = '[AUTH] SIGN_UP_FAIL';
export const SET_SUBMITTING = '[AUTH] SET_SUBMITTING';
export const SIGN_OUT = '[AUTH] SIGN_OUT';
export const SIGN_OUT_SUCCESS = '[AUTH] SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = '[AUTH] SIGN_OUT_FAIL';

export const AuthActions = {
  notSignedIn: () => ({ type: NOT_SIGNED_IN }),
  saveRedirect: url => ({ type: SAVE_REDIRECT, payload: url }),
  receiveUserProfile: user => ({ type: RECEIVE_USER_PROFILE, payload: user }),
  startSignIn: credentials => ({ type: START_SIGN_IN, payload: credentials }),
  signIn: credentials => ({ type: SIGN_IN, payload: credentials }),
  signInSuccess: userData => ({ type: SIGN_IN_SUCCESS, payload: userData }),
  signInFail: err => ({ type: SIGN_IN_FAIL, payload: err }),
  startSignUp: credentials => ({ type: START_SIGN_UP, payload: credentials }),
  signUp: credentials => ({ type: SIGN_UP, payload: credentials }),
  signUpSuccess: userData => ({ type: SIGN_UP_SUCCESS, payload: userData }),
  signUpFail: err => ({ type: SIGN_UP_FAIL, payload: err }),
  setSubmitting: isSubmitting => ({ type: SET_SUBMITTING, payload: isSubmitting }),
  signOut: () => ({ type: SIGN_OUT }),
  signOutSuccess: () => ({ type: SIGN_OUT_SUCCESS }),
  signOutFail: err => ({ type: SIGN_OUT_FAIL, payload: err })
};
